# Cuando ya vaya a usar mi proyecto en produccion usaria:
#		java -jar miapp.jar --spring.profiles.active=SAT
# o en el caso de este proyecto
#		java -jar APIEmployee.jar --spring.profiles.active=PRD
# cuando ya lo ejecute en ambiente productivo

spring.profiles.active=DEV



