spring.application.name=EasyMailTemplate
server.port=8080

# Configuración de la Base de Datos en ambienteDEV
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.datasource.url=${EASYEMAILTEMPLATE_DB_URL_MYSQL_DEV}
spring.datasource.username=${EASYEMAILTEMPLATE_DB_USR_MYSQL_DEV}
spring.datasource.password=${EASYEMAILTEMPLATE_DB_PWD_MYSQL_DEV}

# Esto es para que me acepte subir archivos pesados al servidor para guardar
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB

# Url dominio para pruebas
app.public.base-url=http://localhost:8080

# Security Config
spring.security.jwt.private.key=f7bc0151c0bf618576c8a797d4a0c76065f333f79b17dc159b4a41f4402c6eac
spring.security.jwt.user.generator=AUTH01-FDXSOFT-GEN







